### PR TITLE
Feature/t-SNE addition plus fixes

### PR DESCRIPTION
**Pull request by SamRagusa**

### CODE REVIEW

**Comment by CFlaniganMide** [comment]
Is there a colab or something to look at for this?  I don't have a workflow set up to get this kind of data to test the plot.

**Comment by SamRagusa** [comment]
I created a colab for you to try out  There's a few other function in there with code that exists in another branch, but you can ignore that

https://drive.google.com/file/d/1v2RTu1vBDsBQer1qZXoXlhjMlRTeXke_/view?usp=sharing

**Comment by CrepeGoat** [comment]
so I'm looking at the Colab; I don't see any `import endaq.plot` or anything, so how does it demonstrate that the `endaq-plot` changes in this PR work correctly?

**Comment by CFlaniganMide** [comment]
TSNE plot looks good, poked around a bit and it seems to be working right.  @CrepeGoat endaq.plot gets imported in one of the functions.

**Review by CFlaniganMide — APPROVED** [review]

**Comment by SamRagusa** [comment]
@CrepeGoat  like @CFlaniganMide mentioned endaq.plot functions get imported on line 82 and 84 of the second code block, at the top of the `cloud_correlation_script`  function.

The reason it's done there rather than with the imports at the start of the code block (where they _should_ be normally) is that the `cloud_correlation_script` function is trying to conform to the template for building/modifying custom cloud report scripts I had came up with:
```python
def function_name(files, file_download_url): 
   # Entire cloud script goes here, meaning you could literally copy/paste the default script here

    return output
```

The reason for this format is that at any point you could copy an existing script into there and start debugging/editing it in a way that your dev environment of choice will actually reference the proper code giving you an error, and it's super easy to take a finished script and copy/paste it into cloud.endaq.com which is why the imports need to be there.

I'm gonna write a Confluence doc about this, because it needs some explaining.

**Pull request merged**
